# Generated by Django 5.2 on 2025-05-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='category',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
