# Generated by Django 5.2 on 2025-05-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_homeslider_category_alter_homeslider_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
