# Generated by Django 5.2 on 2026-04-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_homeslider_price_from"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homeslider",
            name="category",
        ),
        migrations.RemoveField(
            model_name="homeslider",
            name="price_from",
        ),
        migrations.AddField(
            model_name="homeslider",
            name="header",
            field=models.CharField(default="test", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homeslider",
            name="path",
            field=models.CharField(default="test-path", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homeslider",
            name="subtitle",
            field=models.CharField(default="test sub", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="homeslider",
            name="image",
            field=models.ImageField(upload_to="homeslider/"),
        ),
    ]
