# Generated by Django 5.2 on 2026-04-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_remove_homeslider_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("new_collection", "New Collection"),
                            ("services", "Services"),
                            ("why_with_us", "Why With Us"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("subtitle", models.CharField(max_length=255)),
                ("icon_name", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
