# Generated by Django 5.2 on 2026-04-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_section"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="icon_name",
            new_name="icon",
        ),
        migrations.AddField(
            model_name="section",
            name="icon_type_is_path",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the icon is a path to an image file or a CSS class name for an icon font.",
            ),
        ),
    ]
