# Generated by Django 5.2 on 2026-04-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
