# Generated by Django 5.2 on 2026-04-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_product_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="new",
            field=models.BooleanField(
                default=False, help_text="Mark product as new arrival"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="trending",
            field=models.BooleanField(
                default=False, help_text="Mark product as trending, listed on homepage"
            ),
        ),
    ]
