# Generated by Django 5.2 on 2026-04-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_size_alter_product_discount_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_types/"),
        ),
    ]
