# Generated by Django 5.2 on 2026-04-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_producttype_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
